name: "Nix Flake CI"
on:
  pull_request:
  push:
jobs:
  check:
    name: Check Nix Flake Status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check --no-build --all-systems
